export const FALLBACK_HOSPITALS = [
  {
    id: 'hosp-1',
    name: 'Evercare Hospital Chuadanga',
    slug: 'evercare-hospital-chuadanga',
    hospitalType: 'Super Specialty Hospital',
    status: 'ACTIVE',
    isFeatured: true,
    address: 'Station Road, Chuadanga Sadar, Chuadanga',
    phone: '+880 761-62588',
    emergencyPhone: '10663',
    email: 'info.chuadanga@evercarebd.com',
    description: 'Evercare Hospital Chuadanga is a multi-disciplinary super-specialty tertiary care hospital in Chuadanga featuring state-of-the-art emergency care, 24/7 ICU support, and advanced surgery.',
    coverUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80',
    facilities: [
      { id: 'f-1', facilityName: '24/7 Emergency & Trauma' },
      { id: 'f-2', facilityName: 'ICU & CCU' },
      { id: 'f-3', facilityName: 'Digital Pathology' },
    ],
    _count: { doctors: 6 },
  },
  {
    id: 'hosp-2',
    name: 'Chuadanga Sadar Hospital',
    slug: 'chuadanga-sadar-hospital',
    hospitalType: 'General Government Hospital',
    status: 'ACTIVE',
    isFeatured: true,
    address: 'Hospital Road, Chuadanga Sadar, Chuadanga',
    phone: '+880 761-62234',
    emergencyPhone: '01712-345678',
    email: 'sadar.chuadanga@dghs.gov.bd',
    description: 'The premier public healthcare institution in Chuadanga District providing comprehensive 24/7 emergency medical, inpatient, outpatient, and maternal healthcare services.',
    coverUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&auto=format&fit=crop&q=80',
    facilities: [
      { id: 'f-4', facilityName: '24/7 Emergency Ward' },
      { id: 'f-5', facilityName: 'Government Blood Bank' },
      { id: 'f-6', facilityName: 'Maternity Unit' },
    ],
    _count: { doctors: 6 },
  },
  {
    id: 'hosp-3',
    name: 'Popular Diagnostic Centre Chuadanga',
    slug: 'popular-diagnostic-centre-chuadanga',
    hospitalType: 'Specialized Diagnostic & Consultation Centre',
    status: 'ACTIVE',
    isFeatured: true,
    address: 'Court Road, Chuadanga Sadar, Chuadanga',
    phone: '+880 761-63345',
    emergencyPhone: '01713-987654',
    email: 'chuadanga@populardiagnostic.com',
    description: 'Leading private diagnostic and specialist doctor consultation center in Chuadanga offering high-resolution MRI, CT Scan, 4D Ultrasonography, and automated pathology laboratory.',
    coverUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop&q=80',
    facilities: [
      { id: 'f-7', facilityName: '1.5T MRI & 128-Slice CT' },
      { id: 'f-8', facilityName: 'Specialist Chambers' },
      { id: 'f-9', facilityName: 'Automated Lab' },
    ],
    _count: { doctors: 6 },
  },
  {
    id: 'hosp-4',
    name: 'Alamdanga Health Care Clinic',
    slug: 'alamdanga-health-care-clinic',
    hospitalType: 'Private Specialized Clinic & Diagnostic Center',
    status: 'ACTIVE',
    isFeatured: true,
    address: 'College Road, Alamdanga Upazila, Chuadanga',
    phone: '+880 7622-56123',
    emergencyPhone: '01718-445566',
    email: 'info@alamdangahealthcare.com',
    description: 'Alamdanga Health Care Clinic is a modern private healthcare facility serving Alamdanga and surrounding areas with 24/7 emergency care, specialist outpatient consultations, and modern lab testing.',
    coverUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=800&auto=format&fit=crop&q=80',
    facilities: [
      { id: 'f-10', facilityName: '24/7 Emergency' },
      { id: 'f-11', facilityName: 'Digital X-Ray' },
      { id: 'f-12', facilityName: 'Pharmacy' },
    ],
    _count: { doctors: 6 },
  },
  {
    id: 'hosp-5',
    name: 'Impulse Health Clinic Chuadanga',
    slug: 'impulse-health-clinic-chuadanga',
    hospitalType: 'Specialized Daycare Clinic & Diagnostic',
    status: 'ACTIVE',
    isFeatured: true,
    address: 'Cinema Hall Road, Chuadanga Sadar, Chuadanga',
    phone: '+880 761-64512',
    emergencyPhone: '01715-112233',
    email: 'impulse.chuadanga@gmail.com',
    description: 'A modern medical consultation center offering specialist doctor chambers, advanced day-care surgery, endoscopy, colonoscopy, and digital diagnostic facilities in Chuadanga.',
    coverUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800&auto=format&fit=crop&q=80',
    facilities: [
      { id: 'f-13', facilityName: 'Day-care Surgery' },
      { id: 'f-14', facilityName: 'Endoscopy Lab' },
      { id: 'f-15', facilityName: 'Specialist Chambers' },
    ],
    _count: { doctors: 6 },
  },
];
