export const FALLBACK_HOSPITALS = [
  {
    id: 'hosp-1',
    name: 'Evercare Hospital Chuadanga',
    slug: 'evercare-hospital-chuadanga',
    hospitalType: 'Super Specialty Hospital',
    status: 'ACTIVE',
    isFeatured: true,
    address: 'Station Road, Chuadanga Sadar, Chuadanga',
    phone: '+880 761-62588',
    emergencyPhone: '10663',
    email: 'info.chuadanga@evercarebd.com',
    description: 'Evercare Hospital Chuadanga is a 470-bed multi-disciplinary super-specialty tertiary care hospital in Chuadanga featuring state-of-the-art emergency care, 24/7 ICU support, and advanced surgery.',
    coverUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80',
    facilities: [
      { id: 'f-1', facilityName: '24/7 Emergency & Trauma' },
      { id: 'f-2', facilityName: 'ICU & CCU' },
      { id: 'f-3', facilityName: 'Digital Pathology' },
    ],
    _count: { doctors: 6 },
  },
  {
    id: 'hosp-2',
    name: 'Chuadanga Sadar Hospital',
    slug: 'chuadanga-sadar-hospital',
    hospitalType: 'General Government Hospital',
    status: 'ACTIVE',
    isFeatured: true,
    address: 'Hospital Road, Chuadanga Sadar, Chuadanga',
    phone: '+880 761-62234',
    emergencyPhone: '01712-345678',
    email: 'sadar.chuadanga@dghs.gov.bd',
    description: 'The premier public healthcare institution in Chuadanga District providing comprehensive 24/7 emergency medical, inpatient, outpatient, and maternal healthcare services.',
    coverUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&auto=format&fit=crop&q=80',
    facilities: [
      { id: 'f-4', facilityName: '24/7 Emergency Ward' },
      { id: 'f-5', facilityName: 'Government Blood Bank' },
      { id: 'f-6', facilityName: 'Maternity Unit' },
    ],
    _count: { doctors: 6 },
  },
  {
    id: 'hosp-3',
    name: 'Popular Diagnostic Centre Chuadanga',
    slug: 'popular-diagnostic-centre-chuadanga',
    hospitalType: 'Specialized Diagnostic & Consultation Centre',
    status: 'ACTIVE',
    isFeatured: true,
    address: 'Court Road, Chuadanga Sadar, Chuadanga',
    phone: '+880 761-63345',
    emergencyPhone: '01713-987654',
    email: 'chuadanga@populardiagnostic.com',
    description: 'Leading private diagnostic and specialist doctor consultation center in Chuadanga offering high-resolution MRI, CT Scan, 4D Ultrasonography, and automated pathology laboratory.',
    coverUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop&q=80',
    facilities: [
      { id: 'f-7', facilityName: '1.5T MRI & 128-Slice CT' },
      { id: 'f-8', facilityName: 'Specialist Chambers' },
      { id: 'f-9', facilityName: 'Automated Lab' },
    ],
    _count: { doctors: 6 },
  },
  {
    id: 'hosp-4',
    name: 'Alamdanga Health Care Clinic',
    slug: 'alamdanga-health-care-clinic',
    hospitalType: 'Private Specialized Clinic & Diagnostic Center',
    status: 'ACTIVE',
    isFeatured: true,
    address: 'College Road, Alamdanga Upazila, Chuadanga',
    phone: '+880 7622-56123',
    emergencyPhone: '01718-445566',
    email: 'info@alamdangahealthcare.com',
    description: 'Alamdanga Health Care Clinic is a modern private healthcare facility serving Alamdanga and surrounding areas with 24/7 emergency care, specialist outpatient consultations, and modern lab testing.',
    coverUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=800&auto=format&fit=crop&q=80',
    facilities: [
      { id: 'f-10', facilityName: '24/7 Emergency' },
      { id: 'f-11', facilityName: 'Digital X-Ray' },
      { id: 'f-12', facilityName: 'Pharmacy' },
    ],
    _count: { doctors: 6 },
  },
  {
    id: 'hosp-5',
    name: 'Impulse Health Clinic Chuadanga',
    slug: 'impulse-health-clinic-chuadanga',
    hospitalType: 'Specialized Daycare Clinic & Diagnostic',
    status: 'ACTIVE',
    isFeatured: true,
    address: 'Cinema Hall Road, Chuadanga Sadar, Chuadanga',
    phone: '+880 761-64512',
    emergencyPhone: '01715-112233',
    email: 'impulse.chuadanga@gmail.com',
    description: 'A modern medical consultation center offering specialist doctor chambers, advanced day-care surgery, endoscopy, colonoscopy, and digital diagnostic facilities in Chuadanga.',
    coverUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800&auto=format&fit=crop&q=80',
    facilities: [
      { id: 'f-13', facilityName: 'Day-care Surgery' },
      { id: 'f-14', facilityName: 'Endoscopy Lab' },
      { id: 'f-15', facilityName: 'Specialist Chambers' },
    ],
    _count: { doctors: 6 },
  },
];

export const FALLBACK_DOCTORS = [
  // Evercare Hospital Chuadanga (6 Doctors)
  {
    id: 'doc-1',
    name: 'Dr. Mahbubur Rahman Chowdhury',
    slug: 'dr-mahbubur-rahman-chowdhury-evercare',
    bmdcNumber: 'A-45892',
    degrees: 'MBBS, FCPS (Cardiology), MD (Cardiology)',
    specialization: 'Senior Consultant Cardiologist',
    experienceYears: 18,
    consultationFee: 1200,
    chamberRoom: 'Block A, 4th Floor, Suite 402',
    phone: '+880 1711-209841',
    photoUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    bio: 'Senior interventional cardiologist specializing in coronary angioplasty, heart failure management, and acute cardiac care.',
    department: { nameEn: 'Cardiology & Heart Care', nameBn: 'কার্ডিওলজি ও হৃদরোগ বিভাগ' },
    hospital: { name: 'Evercare Hospital Chuadanga', slug: 'evercare-hospital-chuadanga', address: 'Station Road, Chuadanga Sadar' },
    schedules: [
      { dayOfWeek: 6, startTime: '04:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 0, startTime: '04:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 1, startTime: '04:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 2, startTime: '04:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 3, startTime: '04:00 PM', endTime: '09:00 PM' },
    ],
  },
  {
    id: 'doc-2',
    name: 'Dr. Selina Parveen',
    slug: 'dr-selina-parveen-evercare',
    bmdcNumber: 'A-56901',
    degrees: 'MBBS, MS (Gynae & Obs), FCPS',
    specialization: 'Consultant Gynecologist & Laparoscopic Surgeon',
    experienceYears: 14,
    consultationFee: 1000,
    chamberRoom: 'Chamber #104, Ground Floor',
    phone: '+880 1819-332145',
    photoUrl: 'https://images.unsplash.com/photo-1594824813566-78a9c2d1b827?w=400&auto=format&fit=crop&q=80',
    bio: 'Specializes in high-risk pregnancies, advanced laparoscopic gynecological surgeries, pain-free normal deliveries, and infertility care.',
    department: { nameEn: 'Gynecology & Obstetrics', nameBn: 'স্ত্রী ও প্রসূতি রোগ বিভাগ' },
    hospital: { name: 'Evercare Hospital Chuadanga', slug: 'evercare-hospital-chuadanga', address: 'Station Road, Chuadanga Sadar' },
    schedules: [
      { dayOfWeek: 6, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 0, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 1, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 2, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 3, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 4, startTime: '03:00 PM', endTime: '08:00 PM' },
    ],
  },
  {
    id: 'doc-3',
    name: 'Dr. Kazi Ariful Haque',
    slug: 'dr-kazi-ariful-haque-evercare',
    bmdcNumber: 'A-38910',
    degrees: 'MBBS, MS (Orthopedics), D-Ortho',
    specialization: 'Trauma & Joint Replacement Surgeon',
    experienceYears: 16,
    consultationFee: 1000,
    chamberRoom: 'Room #205, 2nd Floor',
    phone: '+880 1712-445566',
    photoUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    bio: 'Renowned orthopedic surgeon specializing in knee and hip replacement surgery, complex bone fracture reconstruction, and sports injury rehabilitation.',
    department: { nameEn: 'Orthopedics & Trauma', nameBn: 'অর্থোপেডিক্স ও ট্রমা বিভাগ' },
    hospital: { name: 'Evercare Hospital Chuadanga', slug: 'evercare-hospital-chuadanga', address: 'Station Road, Chuadanga Sadar' },
    schedules: [
      { dayOfWeek: 6, startTime: '05:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 0, startTime: '05:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 1, startTime: '05:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 3, startTime: '05:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 4, startTime: '05:00 PM', endTime: '09:00 PM' },
    ],
  },
  {
    id: 'doc-4',
    name: 'Dr. Nuzhat Fatema',
    slug: 'dr-nuzhat-fatema-evercare',
    bmdcNumber: 'A-61204',
    degrees: 'MBBS, DCH (Pediatrics), FCPS (Paed)',
    specialization: 'Senior Consultant Pediatrician & Neonatologist',
    experienceYears: 11,
    consultationFee: 900,
    chamberRoom: 'Room #108, Pediatric Outdoor',
    phone: '+880 1913-556677',
    photoUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    bio: 'Dedicated pediatrician providing comprehensive newborn care, pediatric asthma management, childhood nutrition counseling, and emergency pediatric care.',
    department: { nameEn: 'Pediatrics & Child Health', nameBn: 'শিশু রোগ বিভাগ' },
    hospital: { name: 'Evercare Hospital Chuadanga', slug: 'evercare-hospital-chuadanga', address: 'Station Road, Chuadanga Sadar' },
    schedules: [
      { dayOfWeek: 6, startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 0, startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 1, startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 2, startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 3, startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 4, startTime: '09:00 AM', endTime: '02:00 PM' },
    ],
  },
  {
    id: 'doc-5',
    name: 'Dr. Towhidul Islam',
    slug: 'dr-towhidul-islam-evercare',
    bmdcNumber: 'A-49021',
    degrees: 'MBBS, MD (Neurology), PhD',
    specialization: 'Consultant Neurologist & Stroke Specialist',
    experienceYears: 15,
    consultationFee: 1200,
    chamberRoom: 'Suite #401, 4th Floor',
    phone: '+880 1715-667788',
    photoUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&auto=format&fit=crop&q=80',
    bio: 'Expert neurologist specializing in stroke treatment, stroke rehabilitation, epilepsy, Parkinson disease, chronic migraine, and peripheral neuropathy.',
    department: { nameEn: 'Neurology & Brain Sciences', nameBn: 'নিউরোমেডিসিন ও ব্রেইন সাইন্স বিভাগ' },
    hospital: { name: 'Evercare Hospital Chuadanga', slug: 'evercare-hospital-chuadanga', address: 'Station Road, Chuadanga Sadar' },
    schedules: [
      { dayOfWeek: 6, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 0, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 1, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 2, startTime: '03:00 PM', endTime: '08:00 PM' },
    ],
  },
  {
    id: 'doc-6',
    name: 'Dr. Sharmeen Sultana',
    slug: 'dr-sharmeen-sultana-evercare',
    bmdcNumber: 'A-53219',
    degrees: 'MBBS, DDV, FCPS (Dermatology)',
    specialization: 'Consultant Dermatologist & Laser Specialist',
    experienceYears: 10,
    consultationFee: 800,
    chamberRoom: 'Chamber #210, 2nd Floor',
    phone: '+880 1817-778899',
    photoUrl: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&auto=format&fit=crop&q=80',
    bio: 'Specialist in modern skin disease treatments, acne scar removal, chronic eczema, skin allergies, hair loss therapy, and clinical laser procedures.',
    department: { nameEn: 'Dermatology & Skin Care', nameBn: 'চর্ম ও এলার্জি রোগ বিভাগ' },
    hospital: { name: 'Evercare Hospital Chuadanga', slug: 'evercare-hospital-chuadanga', address: 'Station Road, Chuadanga Sadar' },
    schedules: [
      { dayOfWeek: 6, startTime: '04:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 0, startTime: '04:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 2, startTime: '04:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 3, startTime: '04:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 4, startTime: '04:00 PM', endTime: '08:00 PM' },
    ],
  },

  // Alamdanga Health Care Clinic (Doctors)
  {
    id: 'doc-7',
    name: 'Dr. Md. Motiur Rahman',
    slug: 'dr-md-motiur-rahman-alamdanga',
    bmdcNumber: 'A-34512',
    degrees: 'MBBS, BCS (Health), FCPS (Medicine), MD (Medicine)',
    specialization: 'Medicine & Diabetes Specialist',
    experienceYears: 16,
    consultationFee: 700,
    chamberRoom: 'Main Building, Room 102',
    phone: '+880 7622-56123',
    photoUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    bio: 'Senior Medicine Specialist providing consultations for diabetes, high blood pressure, asthma, chest diseases, and internal medicine.',
    department: { nameEn: 'Medicine & Diabetes', nameBn: 'মেডিসিন ও ডায়াবেটিস বিভাগ' },
    hospital: { name: 'Alamdanga Health Care Clinic', slug: 'alamdanga-health-care-clinic', address: 'College Road, Alamdanga' },
    schedules: [
      { dayOfWeek: 6, startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 0, startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 1, startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 2, startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 3, startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 4, startTime: '09:00 AM', endTime: '02:00 PM' },
    ],
  },
  {
    id: 'doc-8',
    name: 'Dr. Afroza Begum',
    slug: 'dr-afroza-begum-alamdanga',
    bmdcNumber: 'A-41289',
    degrees: 'MBBS, DGO, FCPS (Gynae)',
    specialization: 'Gynecologist & Obstetrician',
    experienceYears: 12,
    consultationFee: 600,
    chamberRoom: 'Female Block, Room 204',
    phone: '+880 1718-445566',
    photoUrl: 'https://images.unsplash.com/photo-1594824813566-78a9c2d1b827?w=400&auto=format&fit=crop&q=80',
    bio: 'Experienced in normal delivery, high-risk pregnancy care, infertility treatment, and laparoscopic surgery.',
    department: { nameEn: 'Gynecology & Obstetrics', nameBn: 'স্ত্রী ও প্রসূতি রোগ বিভাগ' },
    hospital: { name: 'Alamdanga Health Care Clinic', slug: 'alamdanga-health-care-clinic', address: 'College Road, Alamdanga' },
    schedules: [
      { dayOfWeek: 6, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 0, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 1, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 3, startTime: '03:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 4, startTime: '03:00 PM', endTime: '08:00 PM' },
    ],
  },
  {
    id: 'doc-9',
    name: 'Dr. Tanvir Ahmed',
    slug: 'dr-tanvir-ahmed-alamdanga',
    bmdcNumber: 'A-51920',
    degrees: 'MBBS, DCH, FCPS (Pediatrics)',
    specialization: 'Child & Newborn Health Specialist',
    experienceYears: 10,
    consultationFee: 600,
    chamberRoom: 'Child Care Wing, Room 105',
    phone: '+880 1718-445577',
    photoUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    bio: 'Dedicated pediatrician providing specialized newborn care, vaccination, childhood pneumonia, and pediatric growth counseling.',
    department: { nameEn: 'Pediatrics & Child Health', nameBn: 'শিশু রোগ বিভাগ' },
    hospital: { name: 'Alamdanga Health Care Clinic', slug: 'alamdanga-health-care-clinic', address: 'College Road, Alamdanga' },
    schedules: [
      { dayOfWeek: 6, startTime: '04:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 0, startTime: '04:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 1, startTime: '04:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 2, startTime: '04:00 PM', endTime: '09:00 PM' },
      { dayOfWeek: 4, startTime: '04:00 PM', endTime: '09:00 PM' },
    ],
  },

  // Chuadanga Sadar Hospital (Doctors)
  {
    id: 'doc-10',
    name: 'Dr. Md. Tariqul Islam',
    slug: 'dr-md-tariqul-islam-sadar',
    bmdcNumber: 'A-39812',
    degrees: 'MBBS, BCS (Health), MD (Cardiology)',
    specialization: 'Consultant Cardiologist',
    experienceYears: 15,
    consultationFee: 800,
    chamberRoom: 'Outdoor Room #102, Sadar Hospital',
    phone: '+880 761-62234',
    photoUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&auto=format&fit=crop&q=80',
    bio: 'Leading cardiologist in Chuadanga providing care for hypertension, chest pain, heart attacks, and echo-cardiogram diagnostic evaluations.',
    department: { nameEn: 'Cardiology & Heart Care', nameBn: 'কার্ডিওলজি ও হৃদরোগ বিভাগ' },
    hospital: { name: 'Chuadanga Sadar Hospital', slug: 'chuadanga-sadar-hospital', address: 'Hospital Road, Chuadanga Sadar' },
    schedules: [
      { dayOfWeek: 6, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 0, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 1, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 2, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 3, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 4, startTime: '08:30 AM', endTime: '02:30 PM' },
    ],
  },
  {
    id: 'doc-11',
    name: 'Dr. Shamima Nasrin',
    slug: 'dr-shamima-nasrin-sadar',
    bmdcNumber: 'A-47120',
    degrees: 'MBBS, BCS (Health), MS (Gynae & Obs)',
    specialization: 'Senior Consultant Gynecologist',
    experienceYears: 13,
    consultationFee: 700,
    chamberRoom: 'Maternity Unit, 2nd Floor',
    phone: '+880 761-62235',
    photoUrl: 'https://images.unsplash.com/photo-1594824813566-78a9c2d1b827?w=400&auto=format&fit=crop&q=80',
    bio: 'Experienced government gynecologist providing high quality obstetric and laparoscopic surgical solutions in Chuadanga Sadar Hospital.',
    department: { nameEn: 'Gynecology & Obstetrics', nameBn: 'স্ত্রী ও প্রসূতি রোগ বিভাগ' },
    hospital: { name: 'Chuadanga Sadar Hospital', slug: 'chuadanga-sadar-hospital', address: 'Hospital Road, Chuadanga Sadar' },
    schedules: [
      { dayOfWeek: 6, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 0, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 1, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 2, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 3, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 4, startTime: '08:30 AM', endTime: '02:30 PM' },
    ],
  },
  {
    id: 'doc-12',
    name: 'Dr. Md. Asaduzzaman',
    slug: 'dr-md-asaduzzaman-sadar',
    bmdcNumber: 'A-33190',
    degrees: 'MBBS, BCS (Health), MS (Orthopedics)',
    specialization: 'Senior Orthopedic Surgeon',
    experienceYears: 19,
    consultationFee: 800,
    chamberRoom: 'Orthopedic Block Room #201',
    phone: '+880 761-62236',
    photoUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    bio: 'Highly experienced trauma and fracture reconstruction surgeon handling complex emergency trauma and road accident orthopedic injuries.',
    department: { nameEn: 'Orthopedics & Trauma', nameBn: 'অর্থোপেডিক্স ও ট্রমা বিভাগ' },
    hospital: { name: 'Chuadanga Sadar Hospital', slug: 'chuadanga-sadar-hospital', address: 'Hospital Road, Chuadanga Sadar' },
    schedules: [
      { dayOfWeek: 6, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 0, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 1, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 2, startTime: '08:30 AM', endTime: '02:30 PM' },
      { dayOfWeek: 3, startTime: '08:30 AM', endTime: '02:30 PM' },
    ],
  },
];

export const FALLBACK_DONORS = [
  {
    id: 'donor-1',
    fullName: 'Ashikur Rahman',
    bloodGroup: 'A+',
    age: 26,
    gender: 'Male',
    area: 'Chuadanga Sadar',
    address: 'Station Road, Chuadanga Sadar',
    phone: '01711223344',
    availability: 'available',
    lastDonationDate: '2024-01-15',
    note: 'Regular blood donor, donated 6 times.',
  },
  {
    id: 'donor-2',
    fullName: 'Tanvir Hossain',
    bloodGroup: 'O+',
    age: 29,
    gender: 'Male',
    area: 'Chuadanga Sadar',
    address: 'Court Road, Chuadanga',
    phone: '01722334455',
    availability: 'available',
    lastDonationDate: '2024-02-10',
    note: 'Emergency blood donor available on call.',
  },
  {
    id: 'donor-3',
    fullName: 'Fatema Khatun',
    bloodGroup: 'B+',
    age: 23,
    gender: 'Female',
    area: 'Alamdanga',
    address: 'College Road, Alamdanga',
    phone: '01733445566',
    availability: 'available',
    lastDonationDate: '2023-11-20',
    note: 'Ready to donate for emergency patients.',
  },
  {
    id: 'donor-4',
    fullName: 'Md. Al Amin',
    bloodGroup: 'AB+',
    age: 31,
    gender: 'Male',
    area: 'Damurhuda',
    address: 'Damurhuda Bazar',
    phone: '01744556677',
    availability: 'available',
    lastDonationDate: '2024-03-01',
    note: 'Voluntary blood donor.',
  },
  {
    id: 'donor-5',
    fullName: 'Sabbir Ahmed',
    bloodGroup: 'A-',
    age: 25,
    gender: 'Male',
    area: 'Jibannagar',
    address: 'Jibannagar Bus Stand',
    phone: '01755667788',
    availability: 'available',
    lastDonationDate: '2023-12-05',
    note: 'Rare negative blood group donor.',
  },
  {
    id: 'donor-6',
    fullName: 'Mehedi Hasan',
    bloodGroup: 'O-',
    age: 28,
    gender: 'Male',
    area: 'Chuadanga Sadar',
    address: 'Cinema Hall Road, Chuadanga',
    phone: '01766778899',
    availability: 'available',
    lastDonationDate: '2024-01-28',
    note: 'Universal O- donor available 24/7.',
  },
  {
    id: 'donor-7',
    fullName: 'Anik Chowdhury',
    bloodGroup: 'B-',
    age: 24,
    gender: 'Male',
    area: 'Alamdanga',
    address: 'Alamdanga Railway Station',
    phone: '01777889900',
    availability: 'available',
    lastDonationDate: '2024-02-14',
    note: 'Student at Chuadanga Govt College.',
  },
  {
    id: 'donor-8',
    fullName: 'Rashidul Islam',
    bloodGroup: 'AB-',
    age: 33,
    gender: 'Male',
    area: 'Chuadanga Sadar',
    address: 'Hospital Road, Chuadanga',
    phone: '01788990011',
    availability: 'available',
    lastDonationDate: '2023-10-18',
    note: 'Emergency rare blood donor.',
  },
];
