import { CanonicalSpecialty } from '@/lib/queryNormalizer';
import { IntentType } from '@/lib/aiService';

export interface CasualQueryPattern {
  input: string;
  normalized: string;
  intent: IntentType;
  specialty?: CanonicalSpecialty;
  attribute?: 'CONTACT' | 'LOCATION' | 'FEE' | 'EXPERIENCE' | 'SCHEDULE' | 'SPECIALTY' | 'ICU' | 'EMERGENCY_SERVICE' | 'DIAGNOSTIC';
}

/**
 * Massive, High-Precision Casual Banglish, Bengali, Shorthand & Slang Pattern Dataset (STEP 21)
 * More than 500+ curated patterns mapped to canonical intents and specialties.
 */
export const CASUAL_QUERY_PATTERNS: CasualQueryPattern[] = [
  // ==========================================
  // 1. KIDNEY / NEPHROLOGY PATTERNS
  // ==========================================
  { input: 'kidni', normalized: 'kidney', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidney', normalized: 'kidney', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidny', normalized: 'kidney', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kdin', normalized: 'kidney', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kideny', normalized: 'kidney', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doc', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidney doc', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidney doctor', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni specialist', normalized: 'kidney specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidney specialist', normalized: 'kidney specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni bisessoggo', normalized: 'kidney specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidney bisheshoggo', normalized: 'kidney specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor k ace', normalized: 'kidney doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor ke ace', normalized: 'kidney doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor k k ace', normalized: 'kidney doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor kara ace', normalized: 'kidney doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni er doctor', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni r doctor', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni rog er doctor', normalized: 'kidney disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni problem er doctor', normalized: 'kidney problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni problem', normalized: 'kidney problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidney problem', normalized: 'kidney problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni dekhanor doctor', normalized: 'kidney doctor consultation', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni dekhbe emon doctor', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni check korbo', normalized: 'kidney check doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni check er jonno doctor', normalized: 'kidney check doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni te problem', normalized: 'kidney problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni te somossa', normalized: 'kidney problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni rog', normalized: 'kidney disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidney rog', normalized: 'kidney disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidney treatment', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni treatment', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidney er jonno doctor', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni jonno doctor', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni specialist lagbe', normalized: 'kidney specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor lagbe', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni er bisessoggo', normalized: 'kidney specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'nephro', normalized: 'nephrology', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'nephrology', normalized: 'nephrology', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'nephrologist', normalized: 'nephrologist', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'renal doctor', normalized: 'renal doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'renal specialist', normalized: 'renal specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidney doc lagbe', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doc lagbe', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni k ace', normalized: 'kidney doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni k ache', normalized: 'kidney doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni er doctor k ace', normalized: 'kidney doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni er doctor k ache', normalized: 'kidney doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor chuadanga', normalized: 'kidney doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'chuadanga te kidney doctor', normalized: 'kidney doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'chuadanga kidney specialist', normalized: 'kidney specialist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'chuadanga te kidni doctor', normalized: 'kidney doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'chuadanga te nephrologist', normalized: 'nephrologist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor chai', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor dorkar', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor khujtesi', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor khujchi', normalized: 'kidney doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor dekhaite chai', normalized: 'kidney doctor appointment', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor dekhabo', normalized: 'kidney doctor appointment', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor er info', normalized: 'kidney doctor info', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor er information', normalized: 'kidney doctor info', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor somporke janbo', normalized: 'kidney doctor info', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor ke', normalized: 'kidney doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni specialist ke', normalized: 'kidney specialist list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni bisheshoggo ke', normalized: 'kidney specialist list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor ase naki', normalized: 'kidney doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor ache naki', normalized: 'kidney doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor pawa jabe', normalized: 'kidney doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor paoya jai', normalized: 'kidney doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor kothay', normalized: 'kidney doctor location', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor kothai', normalized: 'kidney doctor location', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor kon hospital e', normalized: 'kidney doctor hospital', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor kon hospitale boshe', normalized: 'kidney doctor hospital', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor er chamber', normalized: 'kidney doctor chamber', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor er chamber kothay', normalized: 'kidney doctor chamber location', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor er fee koto', normalized: 'kidney doctor fee', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor er number', normalized: 'kidney doctor phone', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor er phone number', normalized: 'kidney doctor phone', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor er appointment', normalized: 'kidney doctor appointment', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'kidni doctor dekhanor time', normalized: 'kidney doctor schedule', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'কিডনির ডাক্তার কে আছেন', normalized: 'kidney doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },
  { input: 'কিডনি রোগ বিশেষজ্ঞ', normalized: 'kidney specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEPHROLOGY' },

  // ==========================================
  // 2. PEDIATRICS / CHILD SPECIALIST PATTERNS
  // ==========================================
  { input: 'sisu', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sishu', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'shishu', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisু', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sishu doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'shishu doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'child doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'child specialist', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'baby doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'baccha doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'bachcha doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'bacca doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'baccha der doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'bachader doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'baby specialist', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'child specialist doctor', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu bisessoggo', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sishu bisheshoggo', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'shishu bisheshoggo', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor k ace', normalized: 'child doctor list', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor k k ace', normalized: 'child doctor list', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor kara ace', normalized: 'child doctor list', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor ache?', normalized: 'child doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor lagbe', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor chai', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor dorkar', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'bacchar doctor lagbe', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'baccha osustho', normalized: 'sick child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'bacchar jonno doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'baccha ke kon doctor dekhab', normalized: 'which child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'baby ke kon doctor dekhab', normalized: 'which child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'baby er doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'baccha er doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'child er doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'children doctor', normalized: 'child doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'children specialist', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'pediatric', normalized: 'pediatrician', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'pediatrics', normalized: 'pediatrician', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'pediatrician', normalized: 'pediatrician', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'pediatric doctor', normalized: 'pediatrician', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu specialist', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'shishu specialist', normalized: 'child specialist', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'shishu rog er doctor', normalized: 'child disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'baccha rog er doctor', normalized: 'child disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'bacchar jor', normalized: 'child fever doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'bacchar kashi', normalized: 'child cough doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'bacchar shordi', normalized: 'child cold doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'bacchar pet er problem', normalized: 'child stomach problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'bacchar doctor chuadanga', normalized: 'child doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'chuadanga te sisu doctor', normalized: 'child doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'chuadanga te shishu doctor', normalized: 'child doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'chuadanga child specialist', normalized: 'child specialist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'chuadanga pediatrician', normalized: 'pediatrician chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor kothay', normalized: 'child doctor location', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor kon hospital e', normalized: 'child doctor hospital', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor kon hospitale boshe', normalized: 'child doctor hospital', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor er fee koto', normalized: 'child doctor fee', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor er number', normalized: 'child doctor phone', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor er chamber kothay', normalized: 'child doctor chamber', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'sisu doctor er time', normalized: 'child doctor schedule', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },
  { input: 'শিশু ডাক্তার কে আছেন', normalized: 'child doctor list', intent: 'DOCTOR_SEARCH', specialty: 'PEDIATRICS' },

  // ==========================================
  // 3. GYNECOLOGY / WOMEN'S HEALTH PATTERNS
  // ==========================================
  { input: 'gaini', normalized: 'gynecology', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gyni', normalized: 'gynecology', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gyn', normalized: 'gynecology', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gynae', normalized: 'gynecology', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gynae doctor', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gyni doctor', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doc', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gyni doc', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini specialist', normalized: 'gynecology specialist', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini bisessoggo', normalized: 'gynecology specialist', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini bisheshoggo', normalized: 'gynecology specialist', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gyn doctor', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gyn specialist', normalized: 'gynecology specialist', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gyne doctor', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gyne specialist', normalized: 'gynecology specialist', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gynecology', normalized: 'gynecology', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gynecolgy', normalized: 'gynecology', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gynecologist', normalized: 'gynecologist', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'women doctor', normalized: 'female gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: "women's doctor", normalized: 'female gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'female doctor', normalized: 'female doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'meyeder doctor', normalized: 'women disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'mohila doctor', normalized: 'female doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'mohila der doctor', normalized: 'women disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'meye der doctor', normalized: 'women disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'meyeder specialist', normalized: 'women specialist', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'pregnancy doctor', normalized: 'pregnancy doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'pregnant doctor', normalized: 'pregnancy doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'pregnancy specialist', normalized: 'pregnancy specialist', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'pregnant hole kon doctor', normalized: 'pregnancy doctor recommendation', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'pregnancy er doctor', normalized: 'pregnancy doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'pregnancy check', normalized: 'pregnancy check doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'pregnancy doctor k ace', normalized: 'pregnancy doctor list', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini k ace', normalized: 'gynecology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini ke ace', normalized: 'gynecology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini k k ace', normalized: 'gynecology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor k k ace', normalized: 'gynecology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor kara ace', normalized: 'gynecology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor ache?', normalized: 'gynecology doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor lagbe', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor chai', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor dorkar', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor khujtesi', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor khujchi', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini er doctor', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gyni er doctor', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor chuadanga', normalized: 'gynecology doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'chuadanga te gaini doctor', normalized: 'gynecology doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'chuadanga gyn doctor', normalized: 'gynecology doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'chuadanga gynecologist', normalized: 'gynecologist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'chuadanga te gynae doctor', normalized: 'gynecology doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor kon hospital e', normalized: 'gynecology doctor hospital', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor kon hospitale', normalized: 'gynecology doctor hospital', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor er chamber', normalized: 'gynecology doctor chamber', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor er fee', normalized: 'gynecology doctor fee', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor er number', normalized: 'gynecology doctor phone', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor er phone', normalized: 'gynecology doctor phone', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor er appointment', normalized: 'gynecology doctor appointment', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'gaini doctor er time', normalized: 'gynecology doctor schedule', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'period er problem er doctor', normalized: 'period problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'period problem doctor', normalized: 'period problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'meyeder period er doctor', normalized: 'period problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'uterus doctor', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'female reproductive doctor', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'women health doctor', normalized: 'gynecology doctor', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },
  { input: 'গাইনি ডাক্তার কে আছেন', normalized: 'gynecology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'GYNECOLOGY' },

  // ==========================================
  // 4. CARDIOLOGY / HEART PATTERNS
  // ==========================================
  { input: 'heart', normalized: 'cardiology', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart doctor', normalized: 'cardiology doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart er doctor', normalized: 'cardiology doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart specialist', normalized: 'cardiology specialist', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart bisessoggo', normalized: 'cardiology specialist', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart bisheshoggo', normalized: 'cardiology specialist', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'cardiac doctor', normalized: 'cardiology doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'cardiac specialist', normalized: 'cardiology specialist', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'cardiology', normalized: 'cardiology', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'cardiologist', normalized: 'cardiologist', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'hridrog', normalized: 'cardiology', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'hridrog doctor', normalized: 'cardiology doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'hridrog bisheshoggo', normalized: 'cardiology specialist', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'hridrog er doctor', normalized: 'cardiology doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'hritrog', normalized: 'cardiology', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'hridoy er doctor', normalized: 'cardiology doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'buker doctor', normalized: 'chest/heart doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'buke betha doctor', normalized: 'chest pain doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'chest pain doctor', normalized: 'chest pain doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart problem doctor', normalized: 'heart problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart problem', normalized: 'heart problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'buk betha', normalized: 'chest pain doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'buk betha hole kon doctor', normalized: 'chest pain doctor recommendation', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart check korbo', normalized: 'heart check doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart check er doctor', normalized: 'heart check doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart er problem', normalized: 'heart problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart er osubidha', normalized: 'heart problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart doctor k ace', normalized: 'cardiology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart doctor k k ace', normalized: 'cardiology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart doctor ache?', normalized: 'cardiology doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart doctor lagbe', normalized: 'cardiology doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart doctor chai', normalized: 'cardiology doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart doctor dorkar', normalized: 'cardiology doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart doctor chuadanga', normalized: 'cardiology doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'chuadanga te heart doctor', normalized: 'cardiology doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'chuadanga cardiologist', normalized: 'cardiologist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'cardio doctor', normalized: 'cardiology doctor', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'cardio specialist', normalized: 'cardiology specialist', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'cardio', normalized: 'cardiology', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart er specialist', normalized: 'cardiology specialist', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart er bisessoggo', normalized: 'cardiology specialist', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart doctor er fee', normalized: 'cardiology doctor fee', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart doctor er number', normalized: 'cardiology doctor phone', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'heart doctor er chamber', normalized: 'cardiology doctor chamber', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },
  { input: 'হার্টের ডাক্তার কে আছেন', normalized: 'cardiology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'CARDIOLOGY' },

  // ==========================================
  // 5. MEDICINE / PHYSICIAN PATTERNS
  // ==========================================
  { input: 'medicine', normalized: 'medicine', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medisin', normalized: 'medicine', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medecin', normalized: 'medicine', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicin', normalized: 'medicine', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medisn', normalized: 'medicine', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine doctor', normalized: 'medicine doctor', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medisin doctor', normalized: 'medicine doctor', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine specialist', normalized: 'medicine specialist', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine bisessoggo', normalized: 'medicine specialist', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine bisheshoggo', normalized: 'medicine specialist', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'physician', normalized: 'physician doctor', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'physician doctor', normalized: 'physician doctor', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'general physician', normalized: 'general physician', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'general medicine', normalized: 'general medicine', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'general doctor', normalized: 'general doctor', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine specialist doctor', normalized: 'medicine specialist', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicin er doctor', normalized: 'medicine doctor', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medisin er doctor', normalized: 'medicine doctor', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine er doctor', normalized: 'medicine doctor', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'shorirer onek problem', normalized: 'general problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'onek rokom problem', normalized: 'general problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'general problem er doctor', normalized: 'general medicine doctor', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'general doctor chai', normalized: 'general physician', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'general doctor lagbe', normalized: 'general physician', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine doctor k ace', normalized: 'medicine doctor list', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine doctor k k ace', normalized: 'medicine doctor list', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medisin doctor k ace', normalized: 'medicine doctor list', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medisin doctor k k ace', normalized: 'medicine doctor list', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medisin doctor ache?', normalized: 'medicine doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine doctor ache?', normalized: 'medicine doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine doctor chuadanga', normalized: 'medicine doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'chuadanga te medicine doctor', normalized: 'medicine doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'physician chuadanga', normalized: 'physician chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'physician doctor chuadanga', normalized: 'physician chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine specialist chuadanga', normalized: 'medicine specialist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medisin specialist chuadanga', normalized: 'medicine specialist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine doctor er chamber', normalized: 'medicine doctor chamber', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine doctor er fee', normalized: 'medicine doctor fee', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'medicine doctor er number', normalized: 'medicine doctor phone', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },
  { input: 'মেডিসিন ডাক্তার কে আছেন', normalized: 'medicine doctor list', intent: 'DOCTOR_SEARCH', specialty: 'MEDICINE' },

  // ==========================================
  // 6. DERMATOLOGY / SKIN PATTERNS
  // ==========================================
  { input: 'skin', normalized: 'dermatology', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin doctor', normalized: 'dermatology doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin specialist', normalized: 'dermatology specialist', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin er doctor', normalized: 'dermatology doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin problem doctor', normalized: 'skin problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin problem', normalized: 'skin problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'chormo', normalized: 'dermatology', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'chormo doctor', normalized: 'dermatology doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'chormorog', normalized: 'dermatology disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'chormo rog', normalized: 'dermatology disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'chormorog er doctor', normalized: 'dermatology disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'chormo bisheshoggo', normalized: 'dermatology specialist', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'chormo bishessoggo', normalized: 'dermatology specialist', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'dermatology', normalized: 'dermatology', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'dermatologist', normalized: 'dermatologist', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'derma', normalized: 'dermatology', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'derma doctor', normalized: 'dermatology doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin specialist doctor', normalized: 'dermatology specialist', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'gaye problem', normalized: 'skin allergy doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'gayer problem', normalized: 'skin allergy doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'gaye rash', normalized: 'skin rash doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'rash er doctor', normalized: 'skin rash doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'allergy skin doctor', normalized: 'skin allergy doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'acne doctor', normalized: 'acne dermatologist', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'broner doctor', normalized: 'acne dermatologist', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin doctor k ace', normalized: 'dermatology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin doctor k k ace', normalized: 'dermatology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin doctor ache?', normalized: 'dermatology doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin doctor lagbe', normalized: 'dermatology doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin doctor chai', normalized: 'dermatology doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin doctor dorkar', normalized: 'dermatology doctor', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin doctor chuadanga', normalized: 'dermatology doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'chuadanga te skin doctor', normalized: 'dermatology doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'dermatologist chuadanga', normalized: 'dermatologist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'chormo doctor chuadanga', normalized: 'dermatology doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin specialist chuadanga', normalized: 'dermatology specialist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin doctor er fee', normalized: 'dermatology doctor fee', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin doctor er number', normalized: 'dermatology doctor phone', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'skin doctor er chamber', normalized: 'dermatology doctor chamber', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },
  { input: 'চর্মরোগের ডাক্তার কে আছেন', normalized: 'dermatology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'DERMATOLOGY' },

  // ==========================================
  // 7. ENT (EAR, NOSE, THROAT) PATTERNS
  // ==========================================
  { input: 'ent', normalized: 'ent', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent doctor', normalized: 'ent doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent specialist', normalized: 'ent specialist', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ear doctor', normalized: 'ear doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'kaner doctor', normalized: 'ear doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'kan er doctor', normalized: 'ear doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'nak er doctor', normalized: 'nose doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'nose doctor', normalized: 'nose doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'golar doctor', normalized: 'throat doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'gola doctor', normalized: 'throat doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'throat doctor', normalized: 'throat doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ear nose throat', normalized: 'ent doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ear nose throat doctor', normalized: 'ent doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'nak kan gola', normalized: 'ent specialist', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'nak kan golar doctor', normalized: 'ent doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'nak kan gola specialist', normalized: 'ent specialist', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'kan betha doctor', normalized: 'ear pain doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'nak problem doctor', normalized: 'nose problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'gola betha doctor', normalized: 'throat pain doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ear problem', normalized: 'ear problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'nose problem', normalized: 'nose problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'throat problem', normalized: 'throat problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent doctor k ace', normalized: 'ent doctor list', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent doctor k k ace', normalized: 'ent doctor list', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent doctor ache?', normalized: 'ent doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent doctor lagbe', normalized: 'ent doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent doctor chai', normalized: 'ent doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent doctor dorkar', normalized: 'ent doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent doctor chuadanga', normalized: 'ent doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'chuadanga ent', normalized: 'ent chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'chuadanga te ent doctor', normalized: 'ent doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'kan nak gola doctor', normalized: 'ent doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'kan nak gola specialist', normalized: 'ent specialist', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent specialist er fee', normalized: 'ent doctor fee', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent doctor er number', normalized: 'ent doctor phone', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'ent doctor er chamber', normalized: 'ent doctor chamber', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },
  { input: 'নাক কান গলা ডাক্তার', normalized: 'ent doctor', intent: 'DOCTOR_SEARCH', specialty: 'ENT' },

  // ==========================================
  // 8. ORTHOPEDICS / BONE PATTERNS
  // ==========================================
  { input: 'ortho', normalized: 'orthopedics', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'bone doctor', normalized: 'orthopedic doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'bone specialist', normalized: 'orthopedic specialist', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'haddi doctor', normalized: 'bone doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'haddi er doctor', normalized: 'bone doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'haddi bisheshoggo', normalized: 'bone specialist', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'haddi rog er doctor', normalized: 'bone disease doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'ortho doctor', normalized: 'orthopedic doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'ortho specialist', normalized: 'orthopedic specialist', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'orthopedic', normalized: 'orthopedics', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'orthopedics', normalized: 'orthopedics', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'orthopaedic', normalized: 'orthopedics', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'joint doctor', normalized: 'joint pain doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'joint pain doctor', normalized: 'joint pain doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'bone pain doctor', normalized: 'bone pain doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'hatu betha doctor', normalized: 'knee pain doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'komor betha doctor', normalized: 'back pain doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'back pain doctor', normalized: 'back pain doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'joint problem', normalized: 'joint problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'haddi bhanga doctor', normalized: 'fracture doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'fracture doctor', normalized: 'fracture doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'bone doctor k ace', normalized: 'bone doctor list', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'bone doctor k k ace', normalized: 'bone doctor list', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'ortho doctor k ace', normalized: 'orthopedic doctor list', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'ortho doctor ache?', normalized: 'orthopedic doctor availability', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'ortho doctor lagbe', normalized: 'orthopedic doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'ortho doctor chai', normalized: 'orthopedic doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'ortho doctor dorkar', normalized: 'orthopedic doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'ortho doctor chuadanga', normalized: 'orthopedic doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'chuadanga te ortho doctor', normalized: 'orthopedic doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'orthopedic doctor chuadanga', normalized: 'orthopedic doctor chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'bone specialist chuadanga', normalized: 'bone specialist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },
  { input: 'অর্থোপেডিক্স ডাক্তার', normalized: 'orthopedic doctor', intent: 'DOCTOR_SEARCH', specialty: 'ORTHOPEDICS' },

  // ==========================================
  // 9. NEUROLOGY / BRAIN PATTERNS
  // ==========================================
  { input: 'neuro', normalized: 'neurology', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'brain doctor', normalized: 'neurologist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'brain specialist', normalized: 'neurologist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'mathar doctor', normalized: 'head/neurology doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'matha er doctor', normalized: 'head/neurology doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'neurology', normalized: 'neurology', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'neurologist', normalized: 'neurologist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'neuro doctor', normalized: 'neurology doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'neuro specialist', normalized: 'neurology specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'brain er doctor', normalized: 'neurologist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'matha betha doctor', normalized: 'headache neurology doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'migraine doctor', normalized: 'migraine neurologist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'stroke doctor', normalized: 'stroke neurologist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'stroke specialist', normalized: 'stroke specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'brain problem', normalized: 'brain problem doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'nerve doctor', normalized: 'nerve specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'nerve specialist', normalized: 'nerve specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'snayu doctor', normalized: 'neurology doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'snayu rog er doctor', normalized: 'neurology doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'neuro doctor k ace', normalized: 'neurology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'neuro doctor k k ace', normalized: 'neurology doctor list', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'brain doctor k ace', normalized: 'neurologist list', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'brain doctor ache?', normalized: 'neurologist availability', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'brain specialist lagbe', normalized: 'neurology specialist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'brain doctor chai', normalized: 'neurologist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'brain doctor dorkar', normalized: 'neurologist', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'neurologist chuadanga', normalized: 'neurologist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'chuadanga te neuro doctor', normalized: 'neurologist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'chuadanga brain specialist', normalized: 'brain specialist chuadanga', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },
  { input: 'নিউরোমেডিসিন ডাক্তার', normalized: 'neurology doctor', intent: 'DOCTOR_SEARCH', specialty: 'NEUROLOGY' },

  // ==========================================
  // 10. HOSPITAL SEARCH — CASUAL PATTERNS
  // ==========================================
  { input: 'hospital', normalized: 'hospital', intent: 'VAGUE_HOSPITAL' },
  { input: 'hospital gula', normalized: 'hospitals list', intent: 'HOSPITAL_SEARCH' },
  { input: 'hospital gulo', normalized: 'hospitals list', intent: 'HOSPITAL_SEARCH' },
  { input: 'hospital koyta', normalized: 'hospital count', intent: 'HOSPITAL_COUNT' },
  { input: 'koyta hospital', normalized: 'hospital count', intent: 'HOSPITAL_COUNT' },
  { input: 'koyta hospitale', normalized: 'hospital count', intent: 'HOSPITAL_COUNT' },
  { input: 'hospital k k ace', normalized: 'hospitals list', intent: 'HOSPITAL_SEARCH' },
  { input: 'hospital gula ki ki', normalized: 'hospitals list', intent: 'HOSPITAL_SEARCH' },
  { input: 'hospital gular nam', normalized: 'hospitals list', intent: 'HOSPITAL_SEARCH' },
  { input: 'kon kon hospital ace', normalized: 'hospitals list', intent: 'HOSPITAL_SEARCH' },
  { input: 'kon kon hospitale ace', normalized: 'hospitals list', intent: 'HOSPITAL_SEARCH' },
  { input: 'chuadanga hospital', normalized: 'chuadanga hospitals', intent: 'HOSPITAL_SEARCH' },
  { input: 'chuadanga te hospital', normalized: 'chuadanga hospitals', intent: 'HOSPITAL_SEARCH' },
  { input: 'chuadanga te koyta hospital', normalized: 'hospital count', intent: 'HOSPITAL_COUNT' },
  { input: 'chuadanga te ki ki hospital', normalized: 'hospitals list', intent: 'HOSPITAL_SEARCH' },
  { input: 'hospital lagbe', normalized: 'hospital request', intent: 'VAGUE_HOSPITAL' },
  { input: 'hospital chai', normalized: 'hospital request', intent: 'VAGUE_HOSPITAL' },
  { input: 'hospital khujtesi', normalized: 'hospital request', intent: 'VAGUE_HOSPITAL' },
  { input: 'hospital khujchi', normalized: 'hospital request', intent: 'VAGUE_HOSPITAL' },
  { input: 'valo hospital konta', normalized: 'best hospital ranking disclaimer', intent: 'RANKING_DISCLAIMER' },
  { input: 'bhalo hospital konta', normalized: 'best hospital ranking disclaimer', intent: 'RANKING_DISCLAIMER' },
  { input: 'best hospital', normalized: 'best hospital ranking disclaimer', intent: 'RANKING_DISCLAIMER' },
  { input: 'nearest hospital', normalized: 'nearest hospital', intent: 'HOSPITAL_SEARCH' },
  { input: 'kacher hospital', normalized: 'nearest hospital', intent: 'HOSPITAL_SEARCH' },
  { input: 'hospital er number', normalized: 'hospital phone', intent: 'HOSPITAL_CONTACT' },
  { input: 'hospital er phone', normalized: 'hospital phone', intent: 'HOSPITAL_CONTACT' },
  { input: 'hospital er address', normalized: 'hospital address', intent: 'HOSPITAL_LOCATION' },
  { input: 'hospital kothay', normalized: 'hospital address', intent: 'HOSPITAL_LOCATION' },
  { input: 'hospital kothai', normalized: 'hospital address', intent: 'HOSPITAL_LOCATION' },
  { input: 'hospital kon dike', normalized: 'hospital address', intent: 'HOSPITAL_LOCATION' },
  { input: 'hospital er location', normalized: 'hospital address', intent: 'HOSPITAL_LOCATION' },
  { input: 'emergency hospital', normalized: 'emergency hospital', intent: 'EMERGENCY' },
  { input: 'raat e kon hospital khola', normalized: '24h hospital', intent: 'HOSPITAL_SEARCH' },
  { input: '24 hour hospital', normalized: '24h hospital', intent: 'HOSPITAL_SEARCH' },
  { input: 'hospital e emergency ace?', normalized: 'hospital emergency services', intent: 'EMERGENCY' },
  { input: 'hospital e icu ace?', normalized: 'hospital ICU services', intent: 'HOSPITAL_SEARCH' },
  { input: 'hospital e operation hoy?', normalized: 'hospital surgery', intent: 'HOSPITAL_SEARCH' },
  { input: 'hospital e ki ki service ace?', normalized: 'hospital services', intent: 'HOSPITAL_SEARCH' },

  // ==========================================
  // 11. BLOOD DONOR — CASUAL PATTERNS
  // ==========================================
  { input: 'blood', normalized: 'blood request', intent: 'VAGUE_BLOOD' },
  { input: 'blood lagbe', normalized: 'blood request', intent: 'VAGUE_BLOOD' },
  { input: 'rokto lagbe', normalized: 'blood request', intent: 'VAGUE_BLOOD' },
  { input: 'rokto chai', normalized: 'blood request', intent: 'VAGUE_BLOOD' },
  { input: 'rokto dorkar', normalized: 'blood request', intent: 'VAGUE_BLOOD' },
  { input: 'blood donor', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'blood donar', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'blood donner', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'rokto donor', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'rokto data', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'rokto data lagbe', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'rokto ke dibe', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'blood ke dibe', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'blood donor k ace', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'blood donor k k ace', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'blood donor ache?', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'blood donor pawa jabe?', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'blood donor paoya jabe?', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'o positive', normalized: 'O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'o+', normalized: 'O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'o pos', normalized: 'O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'o+ blood', normalized: 'O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'o positive blood', normalized: 'O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'o positive donor', normalized: 'O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'o pos donor', normalized: 'O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'o plus blood', normalized: 'O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'o plus donor', normalized: 'O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'o positive rokto', normalized: 'O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'o positive rokto lagbe', normalized: 'O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'a positive', normalized: 'A+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'a+', normalized: 'A+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'a pos', normalized: 'A+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'b positive', normalized: 'B+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'b+', normalized: 'B+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'ab positive', normalized: 'AB+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'ab+', normalized: 'AB+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'negative blood', normalized: 'negative blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'negative donor', normalized: 'negative blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'a negative', normalized: 'A- blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'b negative', normalized: 'B- blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'o negative', normalized: 'O- blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'ab negative', normalized: 'AB- blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'kon blood group er donor ace', normalized: 'blood donor availability', intent: 'BLOOD_SEARCH' },
  { input: 'kono donor ace?', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'donor lagbe', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'donor chai', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'donor dorkar', normalized: 'blood donor request', intent: 'VAGUE_BLOOD' },
  { input: 'chuadanga blood donor', normalized: 'chuadanga blood donors', intent: 'BLOOD_SEARCH' },
  { input: 'chuadanga te blood', normalized: 'chuadanga blood request', intent: 'VAGUE_BLOOD' },
  { input: 'chuadanga te o+ donor', normalized: 'chuadanga O+ blood donor', intent: 'BLOOD_SEARCH' },
  { input: 'rokto donor chuadanga', normalized: 'chuadanga blood donors', intent: 'BLOOD_SEARCH' },

  // ==========================================
  // 12. EMERGENCY — CASUAL PATTERNS
  // ==========================================
  { input: 'emergency', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'emergency number', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'emergency number ki', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'emergency te ki korbo', normalized: 'emergency guideline', intent: 'EMERGENCY' },
  { input: 'jhoruri number', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'joruri number', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'joruri help', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'emergency help', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'emergency te kothay jabo', normalized: 'emergency hospital recommendation', intent: 'EMERGENCY' },
  { input: 'raat e emergency', normalized: 'night emergency hospital', intent: 'EMERGENCY' },
  { input: 'ekhon emergency', normalized: 'immediate emergency helpline', intent: 'EMERGENCY' },
  { input: 'urgent', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'urgent help', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'ambulance', normalized: 'ambulance helpline', intent: 'EMERGENCY' },
  { input: 'ambulance number', normalized: 'ambulance helpline', intent: 'EMERGENCY' },
  { input: 'ambulance lagbe', normalized: 'ambulance helpline', intent: 'EMERGENCY' },
  { input: 'ambulance chai', normalized: 'ambulance helpline', intent: 'EMERGENCY' },
  { input: 'ambulance kothay pabo', normalized: 'ambulance helpline', intent: 'EMERGENCY' },
  { input: 'hospital emergency', normalized: 'hospital emergency', intent: 'EMERGENCY' },
  { input: 'emergency hospital', normalized: 'hospital emergency', intent: 'EMERGENCY' },
  { input: 'emergency service', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'jhoruri sheba', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'joruri sheba', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'joruri service', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'emergency contact', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'emergency phone', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: 'emergency er number', normalized: 'emergency helpline', intent: 'EMERGENCY' },
  { input: '999', normalized: 'national emergency 999', intent: 'EMERGENCY' },
  { input: 'hospital emergency number', normalized: 'hospital emergency helpline', intent: 'EMERGENCY' },
  { input: 'doctor emergency', normalized: 'emergency doctor inquiry', intent: 'VAGUE_EMERGENCY' },
  { input: 'emergency doctor', normalized: 'emergency doctor inquiry', intent: 'VAGUE_EMERGENCY' },

  // ==========================================
  // 13. HOSPITAL SERVICE QUESTIONS
  // ==========================================
  { input: 'icu ace?', normalized: 'hospital ICU query', intent: 'HOSPITAL_SEARCH', attribute: 'ICU' },
  { input: 'icu ache?', normalized: 'hospital ICU query', intent: 'HOSPITAL_SEARCH', attribute: 'ICU' },
  { input: 'hospital e icu ace?', normalized: 'hospital ICU query', intent: 'HOSPITAL_SEARCH', attribute: 'ICU' },
  { input: 'kon hospital e icu ace', normalized: 'hospital ICU query', intent: 'HOSPITAL_SEARCH', attribute: 'ICU' },
  { input: 'kon hospitale icu ache', normalized: 'hospital ICU query', intent: 'HOSPITAL_SEARCH', attribute: 'ICU' },
  { input: 'operation hoy?', normalized: 'hospital surgery query', intent: 'HOSPITAL_SEARCH' },
  { input: 'operation kora hoy?', normalized: 'hospital surgery query', intent: 'HOSPITAL_SEARCH' },
  { input: 'surgery hoy?', normalized: 'hospital surgery query', intent: 'HOSPITAL_SEARCH' },
  { input: 'surgery kothay hoy', normalized: 'hospital surgery query', intent: 'HOSPITAL_SEARCH' },
  { input: 'delivery hoy?', normalized: 'hospital delivery query', intent: 'HOSPITAL_SEARCH' },
  { input: 'normal delivery hoy?', normalized: 'hospital delivery query', intent: 'HOSPITAL_SEARCH' },
  { input: 'c-section hoy?', normalized: 'hospital c-section query', intent: 'HOSPITAL_SEARCH' },
  { input: 'c section kothay hoy', normalized: 'hospital c-section query', intent: 'HOSPITAL_SEARCH' },
  { input: 'test kora hoy?', normalized: 'diagnostic tests query', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'blood test kora hoy?', normalized: 'blood test query', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'xray hoy?', normalized: 'x-ray test query', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'mri hoy?', normalized: 'mri test query', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'ct scan hoy?', normalized: 'ct scan test query', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'ultrasonography hoy?', normalized: 'usg test query', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'usg hoy?', normalized: 'usg test query', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'diagnostic test kothay hoy?', normalized: 'diagnostic test locations', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'ei test ta kothay korbo?', normalized: 'diagnostic test inquiry', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'test kothay kora jai?', normalized: 'diagnostic test inquiry', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'chuadanga te test kothay hoy?', normalized: 'diagnostic test inquiry chuadanga', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'kon diagnostic e hoy?', normalized: 'diagnostic center inquiry', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },
  { input: 'kon hospital e test hoy?', normalized: 'hospital diagnostic test inquiry', intent: 'HOSPITAL_SEARCH', attribute: 'DIAGNOSTIC' },

  // ==========================================
  // 14. DOCTOR DETAIL & ATTRIBUTE QUESTIONS
  // ==========================================
  { input: 'doctor er number', normalized: 'doctor phone', intent: 'DOCTOR_CONTACT', attribute: 'CONTACT' },
  { input: 'doctor er phone', normalized: 'doctor phone', intent: 'DOCTOR_CONTACT', attribute: 'CONTACT' },
  { input: 'doctor er mobile', normalized: 'doctor phone', intent: 'DOCTOR_CONTACT', attribute: 'CONTACT' },
  { input: 'doctor kothay boshe', normalized: 'doctor chamber location', intent: 'DOCTOR_LOCATION', attribute: 'LOCATION' },
  { input: 'doctor kon hospital e boshe', normalized: 'doctor chamber location', intent: 'DOCTOR_LOCATION', attribute: 'LOCATION' },
  { input: 'doctor kon chamber e boshe', normalized: 'doctor chamber location', intent: 'DOCTOR_LOCATION', attribute: 'LOCATION' },
  { input: 'doctor er chamber', normalized: 'doctor chamber location', intent: 'DOCTOR_LOCATION', attribute: 'LOCATION' },
  { input: 'doctor er chamber kothay', normalized: 'doctor chamber location', intent: 'DOCTOR_LOCATION', attribute: 'LOCATION' },
  { input: 'doctor er fee koto', normalized: 'doctor consultation fee', intent: 'DOCTOR_FEE', attribute: 'FEE' },
  { input: 'doctor koto ney', normalized: 'doctor consultation fee', intent: 'DOCTOR_FEE', attribute: 'FEE' },
  { input: 'doctor dekhanor fee', normalized: 'doctor consultation fee', intent: 'DOCTOR_FEE', attribute: 'FEE' },
  { input: 'visit fee', normalized: 'doctor consultation fee', intent: 'DOCTOR_FEE', attribute: 'FEE' },
  { input: 'doctor er visiting hour', normalized: 'doctor schedule', intent: 'DOCTOR_SCHEDULE', attribute: 'SCHEDULE' },
  { input: 'doctor kokhon boshe', normalized: 'doctor schedule', intent: 'DOCTOR_SCHEDULE', attribute: 'SCHEDULE' },
  { input: 'doctor kobe boshe', normalized: 'doctor schedule', intent: 'DOCTOR_SCHEDULE', attribute: 'SCHEDULE' },
  { input: 'doctor er schedule', normalized: 'doctor schedule', intent: 'DOCTOR_SCHEDULE', attribute: 'SCHEDULE' },
  { input: 'doctor er time', normalized: 'doctor schedule', intent: 'DOCTOR_SCHEDULE', attribute: 'SCHEDULE' },
  { input: 'doctor er degree ki', normalized: 'doctor qualification', intent: 'DOCTOR_SPECIALTY', attribute: 'SPECIALTY' },
  { input: 'doctor ki specialist', normalized: 'doctor specialty', intent: 'DOCTOR_SPECIALTY', attribute: 'SPECIALTY' },
  { input: 'doctor er qualification', normalized: 'doctor qualification', intent: 'DOCTOR_SPECIALTY', attribute: 'SPECIALTY' },
  { input: 'doctor er experience', normalized: 'doctor experience', intent: 'DOCTOR_EXPERIENCE', attribute: 'EXPERIENCE' },
  { input: 'doctor er profile', normalized: 'doctor profile', intent: 'DOCTOR_SEARCH' },
  { input: 'doctor er info', normalized: 'doctor info', intent: 'DOCTOR_SEARCH' },
  { input: 'doctor somporke bolo', normalized: 'doctor details', intent: 'DOCTOR_SEARCH' },
  { input: 'doctor er details dao', normalized: 'doctor details', intent: 'DOCTOR_SEARCH' },
  { input: 'doctor ke', normalized: 'doctor info', intent: 'DOCTOR_SEARCH' },
  { input: 'ei doctor ke', normalized: 'doctor info', intent: 'DOCTOR_SEARCH' },
  { input: 'ei doctor ki specialist', normalized: 'doctor specialty', intent: 'DOCTOR_SPECIALTY', attribute: 'SPECIALTY' },
  { input: 'tar number ki', normalized: 'doctor phone', intent: 'DOCTOR_CONTACT', attribute: 'CONTACT' },
  { input: 'tar phone number ki', normalized: 'doctor phone', intent: 'DOCTOR_CONTACT', attribute: 'CONTACT' },
  { input: 'tar chamber kothay', normalized: 'doctor chamber location', intent: 'DOCTOR_LOCATION', attribute: 'LOCATION' },
  { input: 'tar fee koto', normalized: 'doctor consultation fee', intent: 'DOCTOR_FEE', attribute: 'FEE' },
  { input: 'tar visiting time ki', normalized: 'doctor schedule', intent: 'DOCTOR_SCHEDULE', attribute: 'SCHEDULE' },
];

/**
 * Fast lookup pattern index for sub-millisecond casual matching
 */
const PATTERN_INDEX: Map<string, CasualQueryPattern> = new Map();
for (const p of CASUAL_QUERY_PATTERNS) {
  PATTERN_INDEX.set(p.input.toLowerCase().trim(), p);
}

/**
 * Match a raw query string against the casual query patterns dataset
 */
export function matchCasualQueryPattern(input: string): CasualQueryPattern | undefined {
  if (!input || typeof input !== 'string') return undefined;
  const cleaned = input.toLowerCase().replace(/[\?\.!,\-_:;\(\)\[\]"'/\\#@$%^&*]/g, ' ').replace(/\s+/g, ' ').trim();
  
  // 1. Direct key match
  if (PATTERN_INDEX.has(cleaned)) {
    return PATTERN_INDEX.get(cleaned);
  }

  // 2. Exact match in raw input
  if (PATTERN_INDEX.has(input.toLowerCase().trim())) {
    return PATTERN_INDEX.get(input.toLowerCase().trim());
  }

  return undefined;
}
